// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSY6P0jxncvXGhfZ4cjOn8qgS6r2-sFS8',
    appId: '1:963146701166:web:6ae1e4f37f5d7147f7897f',
    messagingSenderId: '963146701166',
    projectId: 'task-manager-1828c',
    authDomain: 'task-manager-1828c.firebaseapp.com',
    storageBucket: 'task-manager-1828c.appspot.com',
    measurementId: 'G-K0KCEXGMR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjYsaBp3sg3G6Ero7o4XN-PUlYnmZsLU',
    appId: '1:963146701166:android:42b594e5f356712ff7897f',
    messagingSenderId: '963146701166',
    projectId: 'task-manager-1828c',
    storageBucket: 'task-manager-1828c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA71-S0K7zFFR_tizIaVQRuUCrzD5JZ8bc',
    appId: '1:963146701166:ios:4eba8f2d1b47fce8f7897f',
    messagingSenderId: '963146701166',
    projectId: 'task-manager-1828c',
    storageBucket: 'task-manager-1828c.appspot.com',
    iosClientId: '963146701166-7koc44evfgk08kt5uhc7nd9vib1kqma2.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA71-S0K7zFFR_tizIaVQRuUCrzD5JZ8bc',
    appId: '1:963146701166:ios:4eba8f2d1b47fce8f7897f',
    messagingSenderId: '963146701166',
    projectId: 'task-manager-1828c',
    storageBucket: 'task-manager-1828c.appspot.com',
    iosClientId: '963146701166-7koc44evfgk08kt5uhc7nd9vib1kqma2.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );
}
